### ISSUE TITLE
python 2/3 compatibility

### ISSUE THREAD

**Issue by jknox13** [AllenInstitute/argschema#51]
`argschema.fields.Str()` seems to return `unicode` instead of `str` in python 2.7.13

script:
```
import sys
from argschema import ArgSchema, ArgSchemaParser, fields

class MySchema(ArgSchema):
    string = fields.Str()

def test_string(string):
    if isinstance(string, str):
        print "PASSED!\ntype :: %s" % type(string)
    else:
        print "FAILED!\ntype :: %s" % type(string)

if __name__ == "__main__":
    print "python ::\n%s\n" % sys.version
    print "Test\n--------"
    mod = ArgSchemaParser(schema_type=MySchema)
    test_string(mod.args["string"])
```

output:
```
$ python argschema_issue.py --string test
python ::
2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

Test
--------
FAILED!
type :: <type 'unicode'>
```

**Comment by fcollman** [comment]
This is a marshmallow decision about the way they have implemented their Str field deserialization Field (we have simply imported all their Fields into argschema.field for connivence..  Can I ask why you are interested in returning a str rather than unicode?  Might help me give you a recommendation about how to proceed?

**Comment by JohnGalbraith** [comment]
Also, we think that if you change your test to 
`is_instance(string, basestring)`
it will pass, but we are not sure if that fixes the problem or just works around it. 8-)

**Comment by dyf** [comment]
`isinstance(var, basestring)` doesn't work in py3.

**Comment by jknox13** [comment]
@fcollman I figured that it might be the marshmallow implementation. 
The fix provided by @JohnGalbraith works well for my case!

However FYI, currently:
     `scipy.interpolate.Rbf()` calls `if isinstance(string, str)`

**Comment by fcollman** [comment]
So I would recommend writing your own Field class to deserialize to str rather than unicode... or else convert the parameters to str before passing it to scipy.

**Comment by jknox13** [comment]
@fcollman Yes of course
