### ISSUE TITLE
CLI option --output_json is not an override flag

### ISSUE THREAD

**Issue by JFPerkins** [AllenInstitute/argschema#55]
ArgSchemaParser.output(d, \<path\>) will write to \<path\> even if --output_json \<different-path\> is passed at the command line. This seems inconsistent with the way inputs are handled, where a command-line override will take precedence over the input dictionary that is passed to ArgSchemaParser, or even the inputs in a json file.

**Comment by fcollman** [comment]
do you mean ArgSchemaParser.output(d) will write the dictionary d to <path> that was specified in the input_json, even if --output_json <different-path> was passed by the command line?

**Comment by JFPerkins** [comment]
Sorry, ArgSchemaParser.output(d, \<path\>) will write the dictionary d to \<path\> regardless of what was in either the input_json or with --output_json.

**Comment by fcollman** [comment]
After some discussion I think we decided this was not a bug or a feature we are going to change in the near future... maybe if we implement a feature which tracks the provenance of each element of the dictionary we might reconsider this, but without that infrastructure this would be hard.
