### ISSUE TITLE
Unable to add additional parser arguments:

### ISSUE THREAD

**Issue by nicain** [AllenInstitute/argschema#62]
I have an entry-point that I want additional arguments, beyond those used by argschema:

```
> foo --version
```

```
> foo --input_json blah.json
```

Because the parse argument is instantiated in utils, and parsed immediately when ArgSchemaParse is constructed, I have no option to inject this arg.

**Comment by fcollman** [comment]
http://marshmallow.readthedocs.io/en/latest/api_reference.html#module-marshmallow.decorators

You can use this functionality to raise custom exceptions if values in a schema are certain ways.

**Comment by nicain** [comment]
Closed resolved xref #63
