### ISSUE TITLE
Having NumpyArray in schema results in warning logs about invalid type.

### ISSUE THREAD

**Issue by JFPerkins** [AllenInstitute/argschema#66]
NumpyArray inherits from marshmallow.fields.List, and sets the list type as marshmallow.fields.Field. When the argument parser is being built, the list handling logs a warning if it can't find a type to pass to argparse which means that all NumpyArrays result in a warning since Field isn't in the type map.

**Comment by fcollman** [comment]
Yeah I agree this is annoying and should be cleaned up.
